name = "lightoflife-couple"
main = "src/index.tsx"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[d1_databases]]
binding       = "DB"
database_name = "lightoflife-db"
database_id   = "662b3fb9-e46d-4b0e-abfd-2380a9e70fe9"

[[kv_namespaces]]
binding = "KV"
id      = "75bddd6da7f1418fad31e1902cda3ae0"

